name: Issue Opened - Call OpenAI

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  run-openai:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Install poppler-utils
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Extract issue details
        id: issue
        run: |
          ISSUE_BODY=$(echo "${{ github.event.issue.body }}" | base64 | tr -d '\n' | tr -d '\r')
          echo "ISSUE_BODY=$ISSUE_BODY" >> $GITHUB_OUTPUT

      - name: Wait for the file to become available
        run: sleep 5

      - name: Fetch PDF Attachment
        id: fetch_pdf
        run: |
          echo "Issue body: ${{ github.event.issue.body }}"
          ATTACHMENT_URL=$(echo "${{ github.event.issue.body }}" | grep -Eo 'https://[^ ]+\.pdf' || true)
          if [ -n "$ATTACHMENT_URL" ]; then
            echo "Found PDF URL: $ATTACHMENT_URL"
            curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -D headers.txt -o issue.pdf "$ATTACHMENT_URL"
            if [ $? -ne 0 ] || ! grep -q '200 OK' headers.txt; then
              echo "Error: Unable to download PDF or invalid response (not 200 OK)."
              exit 1
            fi
            echo "Response Headers:"
            cat headers.txt
            echo "Downloaded File Details:"
            file issue.pdf
            ls -lh issue.pdf
            head -c 100 issue.pdf | xxd
            if ! file issue.pdf | grep -q 'PDF document'; then
              echo "Error: The downloaded file is not a valid PDF."
              exit 1
            fi
            echo "PDF_PATH=issue.pdf" >> $GITHUB_OUTPUT
          else
            echo "No PDF URL found in the issue body."
            echo "PDF_PATH=" >> $GITHUB_OUTPUT
          fi

      - name: Build TypeScript
        run: npm run build

      - name: Call OpenAI
        id: openai_call
        run: |
          if [ -n "${{ steps.fetch_pdf.outputs.PDF_PATH }}" ]; then
            echo "PDF file path: ${{ steps.fetch_pdf.outputs.PDF_PATH }}"
            RESPONSE=$(node dist/call_openai.js \
              "${{ env.OPENAI_API_KEY }}" \
              "${{ steps.issue.outputs.ISSUE_BODY }}" \
              "${{ steps.fetch_pdf.outputs.PDF_PATH }}")
          else
            echo "No PDF file provided. Proceeding with prompt only."
            RESPONSE=$(node dist/call_openai.js \
              "${{ env.OPENAI_API_KEY }}" \
              "${{ steps.issue.outputs.ISSUE_BODY }}" "")
          fi
          echo "response=$RESPONSE" >> $GITHUB_OUTPUT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Comment on the issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            **OpenAI Response:**
            ${{ steps.openai_call.outputs.response }}
